import { bfs } from "./BFS";
import { dfs } from "./DFS";
import { dijkstra } from "./dijkstras";
import { gfs } from "./GreedyFirstSearch";
import { aStar } from "./aStar";
import { biDijkstra } from "./biDijkstras";
export { dfs, bfs, dijkstra, gfs, aStar, biDijkstra };
export const ASTAR = "A* Search";
export const BFS = "Breadth-First Search";
export const DFS = "Depth-First Search";
export const DIJ = "Dijkstra's Algorithm";
export const GFS = "Greedy Best-First Search";
export const BDIJ = "Bi-Directional Dijkstra's Algorithm";
